name: GitHub Actions Demo
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: ls -al 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -al 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: python --version
      - name: Build and deploy to gh-pages
        run: |
          pip install mkdocs
          mkdocs gh-deploy --force
      - name: cours-devops
        uses: juhrlass/mqtt-action@master
        with:
          protocol: mqtt
          host: broker.hivemq.com
          port: 1883
          topic: "guinee"
          message: "Le site web du repo ${{ github.repository }} a bien Ã©tÃ© deployÃ© par ${{ github.actor }}"
          username: ''
          password: '' 
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
